### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Mordillo98** [LinusDierheimer/fastfetch#1]
I'm running archlinux kernel 5.11 (installed from Feb 2021 ISO) without a GUI (no XOrg).  It boots directly into terminal.

I'm getting a "Segmentation Fault (core dumped)" at the resolution line when I run fastfetch.  

Neofetch will show that line as "Resolution: preferred".

You can reproduce the issue by booting into a newly created VM with the latest archlinux live ISO, and install archlinux with this script.  It wipes /dev/sda by default but you can modify that script if needed after cloning it.

pacman -Sw glibc lib32-glibc
Then enable the testing repo in /etc/pacman.conf
pacman -Syy
pacman -S glibc lib32-glibc

pacman -Sy git
git clone https://github.com/Mordillo98/archlinuxinstall
cd archlinuxinstall
chmod +x minimalarchinstall.sh
./minimalarchinstall.sh

reboot.  Install your package "yay -S fastfetch-git"

do the fastfetch command.  You'll see the problem.

Thx !

**Comment by LinusDierheimer** [comment]
Sadly i don't have the time to look into such edge cases yet (This is a very very new project i develop in my free time). But i just did a rewrite of the resolution code, now it just shouldn't output the "Resolution: " line on your system. Can you confirm this? In this case i will close this issue. Otherwise please post the output of "fastfetch --recache --show-errors". Thanks.

I am not a friend of putting default values when an error occurs, so probably your "preferred" will never show in fastfetch. But im planing to implement a feature to overwrite values with own strings (via flag or file) for these cases.

**Comment by Mordillo98** [comment]
Tested your new code, problem fixed.  :)  Good job !   You can upload it to ArchLinux AUR if you already didn't do it.

**Comment by LinusDierheimer** [comment]
Closing this. Thanks for the report. The AUR always automatically fetches the latest commit.
