### ISSUE TITLE
Show CPU usage ( summary or per core )

### ISSUE THREAD

**Issue by CarterLi** [LinusDierheimer/fastfetch#111]
Is it possible? Neofetch used to support it but they removed this feature recently because of inaccurate

# Why the change is sensible:

Very high CPU usage means that your computer ( or server ) may lag heavily. Very useful metric

**Comment by LinusDierheimer** [comment]
I think the will suffer from the same problem as neofetch. CPU usage has a lot of very thin spikes / downs that don't represent the actual current load. This is why all the cpu usages take some short time to collect data and then display the average. KSysGuard, on my system for example, takes the average of every 0.5 seconds and forms a nice looking graph out of this data. I think you can see why this is not something fastfetch would benefit from, since the main selling goal of speed would be busted for this feature.

Second, fastfetch itself uses a lot of cpu for a very short time (multithreaded etc) and we would measure at exactly this moment, so we will always get a too high usage.

I am not against  a module displaying this information, so if you have a solution for those problems and are willing to implement it, i am happy to merge.
