### ISSUE TITLE
allow for typing it as "ffetch"

### ISSUE THREAD

**Issue by LethalManBoob** [LinusDierheimer/fastfetch#115]
note the double f.
This makes it quicker and more efficient.

**Comment by LinusDierheimer** [comment]
Auto providing multiple names for the same executable with same arguments is considered bad practice, because it drastically rises the risk of name collisions (especially when using shorten names).

It is up to the user to provide own shortcuts.

For example, put `alias ffetch='fastfetch'` in your `~/.bashrc`, `~/.zshrc` or whatever init file your shell uses.

If you want to have it system wide, create a file `/usr/local/bin/ffetch` with the following content:
```bash
#!/bin/env sh
fastfetch "$@"
```
