### ISSUE TITLE
AUR Stuff

### ISSUE THREAD

**Issue by Samisafool** [LinusDierheimer/fastfetch#125]
The README says it builds for both fastfetch and flashfetch, but you only build for fastfetch

Also paru isn't updating it when you push, paru bug or something on your side?

**Comment by LinusDierheimer** [comment]
The repository contains source code for both fastfetch and flashfetch, that is why the README states this. It doesn't make sense for the PKGBUILD to build flashfetch, as it is intended to be configured only at compile time. If you want compile time configuration, you need to clone the repository yourself and edit the source code.

The PKGBUILD automatically updates its version during building if a new commit is available. I manually update the version if something else needs to be changed in the PKGBUILD too. Otherwise it is explicitly unwanted: https://wiki.archlinux.org/title/Arch_User_Repository#Flagging_packages_out-of-date. You need to run `paru -S --needed fastfetch-git` to update yourself. This applies to all `*-git` packages in the AUR btw.

**Comment by Samisafool** [comment]
Huh, I thought it would autoupdate all `*-git` packages, I saw that mentioned somewhere.

**Comment by LinusDierheimer** [comment]
No, AUR managers just compare the version field with the version installed. If remote is newer, they update. So automatically updates only come when i bump the version because of a change in the build process etc, mere versions bumps are forbidden: VCS packages are not considered out of date when the pkgver changes, do not flag them as the maintainer will merely unflag the package and ignore you. AUR maintainers should not commit mere pkgver bumps.

**Comment by Samisafool** [comment]
From readme:

> At the moment, i only package for the AUR. This package will install **both the fastfetch and the flashfetch binary** (with default configuration), as well as the bash completion.

> The repository contains source code for both fastfetch and flashfetch, that is why the README states this.

I don't think that checks out. Maybe change the wording a little?

**Comment by LinusDierheimer** [comment]
You are right, this is outdated. Old PKGBUILD did indeed install flashfetch. Will change that.

**Comment by artixnous** [comment]
I'm packaging it for Artix, please change the arch=("any") array to the actually CPU architectures. 'any' is meant for scripts, themes, fonts etc, not binaries. Cheers!

**Comment by LinusDierheimer** [comment]
Done
