### ISSUE TITLE
Custom Themes?

### ISSUE THREAD

**Issue by davigamer987** [LinusDierheimer/fastfetch#132]
I want to use a custom neofetch theme (https://raw.githubusercontent.com/xerolinux/xero-nord-git/main/Configs/Home/.config/neofetch/config.conf)

Can Support for this be added?

**Comment by LinusDierheimer** [comment]
Neofetch and fastfetch theming are working extremely different, because fastfetch is compiled, so you can't just execute user provided code. That is the reason fastfetch is themed only with command line arguments, which are limited in the current implementation. I'm working on feature parity with neofetch, but don't expect it soon.

**Comment by davigamer987** [comment]
Ok
