### ISSUE TITLE
Void Linux shows up as unknown

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#14]
Here's the output on Void:
![voidunknown](https://user-images.githubusercontent.com/82701459/115611686-afc67d00-a2ea-11eb-98aa-f004ffc3fce9.png)
This is after the void support was added ofcourse.

PR #15 fixes this

**Comment by DarNCelsius** [comment]
/etc/os-release:

NAME="void"
ID="void"
DISTRIB_ID="void"
PRETTY_NAME="void"

Is it the quotes?

**Comment by DarNCelsius** [comment]
Manjaro:

NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

**Comment by LinusDierheimer** [comment]
With the latest commit, logo detection now askes the os module for the os name. This brings a) better performance as we parse /etc/os-release only one time and b) better detection because this code can handle quotes (which indeed was the problem) and parses more than the ID field, so it should eval a result in more cases. You can close this issue if the latest version works (i cant test void linux right now).

**Comment by DarNCelsius** [comment]
Nice! Void is recognized:
![voidworks](https://user-images.githubusercontent.com/82701459/115780037-fa162f80-a3b8-11eb-9dba-11932e02b8b3.png)
It picked up the Terminal font too I see.
I was toying around with regexes to try a better solution, but I couldn't come up with anything. :)
