### ISSUE TITLE
WSL Support?

### ISSUE THREAD

**Issue by amzon-ex** [LinusDierheimer/fastfetch#174]
Is it possible to add WSL support to fastfetch? Most things work out of the box and that's great, but things like GPU names do not display correctly (since WSL uses a virtual GPU I guess...). Just to cite an example, screenfetch displays these things correctly in WSL (it uses a different technique to display GPU names). Also, themes, icons, cursors - these don't really have a meaning in raw WSL, yet - since with WSLg, you can run graphical applications, the theming is almost non-existent by straightforward means. Also, on my device, the screen refresh rate shows incorrectly (though I suspect this might be something to do with WSL itself).

**Comment by luni3359** [comment]
That could turn out to be a major maintaining burden but right now on the readme it says that it only supports linux and android.

**Comment by LinusDierheimer** [comment]
I just found the time to install windows, to test it in WSL, but i would say, it works pretty great:
* GPU names: fastfetch displays the GPUs, as they are exposed to WSL, There is no way to get a "better" name. Screenfetch just doesn't display them at all for me, neofetch displays them even worse.
* Theme, Icons, Font, Cursor: in my installation it fails to detect them, because no package beside DEs should install theme configurations. But if they are configured, it makes sense to display them, as they are actually used to theme WSLg applications, as far as i can tell. I think that if somebody configured them, there is a good chance that this person will use WSLg.
* The screen refresh rates seem to be limited to 60Hz for WSL, there is nothing i can do about it. Maybe don't display it in WSL sessions?

What i will update, is that "on WSL" is added to the OS output.

Besides that, can you please be more specific about what to change?

**Comment by amzon-ex** [comment]
Thanks for making the time to test it out!

In my case, screenfetch correctly displays the GPU name: `NVIDIA GeForce RTX 3050 Ti Laptop GPU` whereas fastfetch/neofetch shows: `Microsoft Corporation Device 008e`. That's probably what libpci outputs - when I checked the code of screenfetch I found that it first makes queries for manufacturer-specific cards (using `nvidia-smi` for NVIDIA cards, for instance, but that I guess won't work if nvidia-smi is not installed). If it doesn't find any, then it falls back to libpci.

The other points you made, make sense. I understand the picture. As I said, most of the things already work since it's Linux anyway - indicating that it's running on WSL or another operating system would be nice... and if something could be done about the GPU thing. Other than that, even I don't have anything else in mind rn.

**Comment by LinusDierheimer** [comment]
I just looked up `nvidia-smi` and `screenfetch` source code, and this seems to be something that only works on nvidia. But i can't really implement it, since i only have an AMD GPU. 
I greped through the whole file system, but i didn't found any match with my GPU names, so there is a high chance that there is no generic solution.

**Comment by amzon-ex** [comment]
Hi, does this neofetch issue discussion: https://github.com/dylanaraps/neofetch/issues/1646 help in some way? It uses `glxinfo` and different users seem to have tried it out for both AMD and NVIDIA. I checked on my system, and the NVIDIA solution shows "D3D12 (NVIDIA GeForce RTX 3050 Ti Laptop GPU)"

**Comment by LinusDierheimer** [comment]
TBH i don't want to use GL / GLX / EGL etc for gpu detection, because it has the problem of only supporting one GPU. For example i have an integrated GPU and an external GPU, and `glxinfo` always shows only one GPU, which one depends on what the `DRI_PRIME` env variable is set to.

I already have an libpci fallback using vulkan, but currently vulkan seems to be software only in WSL. OpenCL, which also supports multi gpu, just doesn't seem to be supported at all.

As a site note, i just pushed some improvements for WSL, can you please test the following?
* Host should show `Windows Subsytem for Linux`
* WM should show `WSLg (Wayland)`, if WSLg is running
* Cursor shouldn't show anymore, because WSLg uses the native windows cursors

**Comment by amzon-ex** [comment]
> Host should show Windows Subsytem for Linux
> WM should show WSLg (Wayland), if WSLg is running

Thanks, tested it out, works fine!

> Cursor shouldn't show anymore, because WSLg uses the native windows cursors

This is not true, I believe. I use WSLg and it shows Ubuntu cursors (this has been a point of complaint in the WSLg repo, as far as I remember - you cannot customise these much either). 

> TBH i don't want to use GL / GLX / EGL etc for gpu detection, because it has the problem of only supporting one GPU. For example i have an integrated GPU and an external GPU, and glxinfo always shows only one GPU, which one depends on what the DRI_PRIME env variable is set to.

I totally get your point, makes sense. However, I'd like to comment that showing *two* "Microsoft Corporation Device 008" is more unhelpful than just displaying one GPU. Don't you agree?

**Comment by LinusDierheimer** [comment]
I'd argue that too, but it is difficult to implement, because I would need a way to tell "this pci provided GPU name is not good enough, lets detect with OpenGL". Writing an OpenGL implementation to be solely used on WSL is honestly not worth the time.

**Comment by amzon-ex** [comment]
> I'd argue that too, but it is difficult to implement, because I would need a way to tell "this pci provided GPU name is not good enough, lets detect with OpenGL". Writing an OpenGL implementation to be solely used on WSL is honestly not worth the time.

I get your point. By the way - since WSL *always* will produce un-useful output using libpci for the GPU (feel free to correct me based on a major use-case) can you not just use OpenGL if you detect WSL? 

(However: WSL has good(?) NVIDIA GPU support and if you have multiple of them, nvidia-settings is the way to go anyway. )
