### ISSUE TITLE
Warnings while compiling

### ISSUE THREAD

**Issue by Samisafool** [LinusDierheimer/fastfetch#182]
# General description of bug:
```
[ 97%] Building C object CMakeFiles/libfastfetch.dir/src/modules/opencl.c.o
[ 97%] Built target libfastfetch
[ 98%] Building C object CMakeFiles/fastfetch.dir/src/fastfetch.c.o
[100%] Linking C executable fastfetch
lto-wrapper: warning: using serial compilation of 4 LTRANS jobs
lto-wrapper: note: see the ‘-flto’ option documentation for more information
[100%] Built target fastfetch
Consolidate compiler generated dependencies of target libfastfetch
[ 97%] Built target libfastfetch
[ 98%] Building C object CMakeFiles/flashfetch.dir/src/flashfetch.c.o
[100%] Linking C executable flashfetch
lto-wrapper: warning: using serial compilation of 2 LTRANS jobs
lto-wrapper: note: see the ‘-flto’ option documentation for more information
[100%] Built target flashfetch
```

Using the AUR package on Arch Linux. These didn't happen before.

# Often helpful questions:
* Does the issue occur across multiple terminal emulators? N/A
* Does the issue occur across multiple shells? (bash, zsh, fish, etc) N/A

Output of `fastfetch --version`:
```
//paste here
```

Output of `fastfetch --load-config devinfo`:
```
//paste here
```

Output of `fastfetch --load-config devinfo-verbose`:
```
//paste here
```

Output of `fastfetch --list-features`:
```
//paste here
```

**Comment by LinusDierheimer** [comment]
From [StackOverflow](https://stackoverflow.com/questions/72218980/gcc-v12-1-warning-about-serial-compilation):
> gcc was also upgraded from `v11.2` to `v12.1`

> you can try `-flto=1` or `-flto=auto` to get rid of the warning

So a pretty recent change to the gcc compiler. `-flto` is added to the compile flags using CMakes [INTERPROCEDURAL_OPTIMIZATION](https://cmake.org/cmake/help/latest/variable/CMAKE_INTERPROCEDURAL_OPTIMIZATION.html) property, and there is no way to modify it (yet). So i guess we have to wait for CMake to catch up.

But as far as i understand it, this isn't a problem, because it uses auto by default, and just tells us that we can explicitly specify the amount of parallel jobs to compile.

**Comment by LinusDierheimer** [comment]
https://gitlab.kitware.com/cmake/cmake/-/issues/23640
