### ISSUE TITLE
Difference in behaviour on startup

### ISSUE THREAD

**Issue by amzon-ex** [LinusDierheimer/fastfetch#250]
# General description of bug:

Fastfetch produces different output on startup compared to what it produces when run from the command line. I have included fastfetch in my *zshrc* file so that the output is displayed when the shell starts.

I'm on WSL on Windows 11.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/45428344/191820091-62b187f8-40af-4008-b8e2-79f87094ec01.png)

Output of `fastfetch --version`:
```
1.7.2
```

**Comment by LinusDierheimer** [comment]
All modules that are different are ones that get cached, maybe some caching mechanism doesn't work in WSL. 

Try adding `--recache` and report back if that solves the issue.

**Comment by amzon-ex** [comment]
@LinusDierheimer 
Should I add `--recache` to startup or when I run it again?

If you'd not noticed it already, the startup output is incorrect in reporting the resolution. Running it again works fine.

**Comment by LinusDierheimer** [comment]
I was first going after the GPU in the second picture, because it shows GPU, which i disabled for WSL some time ago, because it will always be the same on every system. You might still have the `~/.cache/fastfetch/GPU.ffc{s,v}` files, you should delete them.

About the resolution, i am pretty sure its the values it gets from the wayland compositor, because it correctly detects wayland. Maybe its not fully started when fastfetch makes the first request. If that is the case, there is nothing i can do about that.

I am currently spinning up a Windows 11 VM, to see if i can reproduce.

**Comment by amzon-ex** [comment]
@LinusDierheimer 

You're right, deleting the GPU cache files does remove that output. Waiting to get your results on the other issue.

**Comment by LinusDierheimer** [comment]
I was able to replicate it, but it is WLSgs wayland compositor that advertises 640x480 directly after a fresh start, so there is noting fastfetch can do about it.

Adding a small delay before fastfetch executes solves the issue, but if you really want to have it fixed you should open an issue upstream.

Other tools that display resolution have the same problem...
