### ISSUE TITLE
Gnome Terminal

### ISSUE THREAD

**Issue by Vsrq** [LinusDierheimer/fastfetch#334]
# General description of bug:
When opening gnome-terminal from a keybind with fastfetch in .bashrc, the opening animation is non-existent and just pops up suddenly. 

When opening gnome-terminal from the icon, it freezes for a bit and sluggishly opens. I've tested this on Ubuntu 22.04 & 22.10 as well as Debian 11 Stable & Unstable.

**Comment by jumps-are-op** [comment]
This could be caused by a lot of different reasons

It could be gnome-terminal dose not support printing a lot output or linewrap being off while playing opening animation

Try using `fastfetch --disable-linewrap 0 &>/dev/null` instead in .bashrc

Or try using another terminal (that also have opening animation) and check if that also freezes when using fastfetch in .bashrc.

**Comment by Vsrq** [comment]
I did some more testing and figured that fastfetch wasn't the cause of the issue. Seems like it has something to do with starship prompt. My apologies.
