### ISSUE TITLE
Rename Resolution module

### ISSUE THREAD

**Issue by LinusDierheimer** [LinusDierheimer/fastfetch#393]
The Resolution module does much more than just showing the resolution, for example the refresh rate or the brightness. I propose to use a better name, for example
* `Display`
* `Monitor`
* `Screen`

Personally i am leaning towards Display. 

Your opinion @CarterLi?

**Comment by CarterLi** [comment]
Display is ok for me

**Comment by CarterLi** [comment]
Brightness is now a separate module, because brightness maps to physical display, while resolution maps to virtual display. For example, if you set an external display to a copy of the internal display, there will be one virtual display and one resolution, but there are still two physical displays so there are still two brightness values

**Comment by CarterLi** [comment]
Done in https://github.com/LinusDierheimer/fastfetch/commit/f4a58036fa68e6efbba83ac142211f6f110721bf
