### ISSUE TITLE
Monitor detection cache issues

### ISSUE THREAD

**Issue by DarNCelsius** [LinusDierheimer/fastfetch#74]
This is probably related to my earlier comment in the last issue #73 where the display was not detected.

Here's today's output:
![xrandrrecache](https://user-images.githubusercontent.com/82701459/124380958-353db480-dcc0-11eb-883d-8748d0387e25.png)
I don't think reading from cache is useful when detecting monitors...

**Comment by LinusDierheimer** [comment]
I implemented caching for resolution, because it a typical workflow monitors aren't changed too often and detection was time expensive. In the current state however, i managed to get some decent performance (especially since XWayland is never used), so i will remove caching for it in the next commit.
