### ISSUE TITLE
Installation is not very intuitive

### ISSUE THREAD

**Issue by whyadamsalt** [LinusDierheimer/fastfetch#76]
A nice install.md file would be useful. I followed all the steps and still it didn't build correctly.

**Comment by LinusDierheimer** [comment]
Well there aren't any instruction on how to install it, as this is very distribution dependent, and should therefore be handled by the package manager or be done manually. 
The build instructions however should work flawlessly if you installed all needed dependencies and followed them correctly. If you need help with it, post the error output.
If the build succeeded you can copy over the executable to any folder in your path to have it available globally (for example `/usr/local/bin/`). Writing a package script, if not done by anybody else, would be the best way of course.
As a reference you can look at the AUR PKGBUILD script [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fastfetch-git).

**Comment by LinusDierheimer** [comment]
Any updates on this?

**Comment by whyadamsalt** [comment]
Yeah all of the dependencies have to be built from source. It's a very convoluted method and I feel like adding an installation script would be much more better.

**Comment by LinusDierheimer** [comment]
My guess is using ubuntu (or a ubuntu based) distribution, since the required library headers are not bundled with the package providing the library. Ubuntu provides a different package including those, very often packagename-dev. For example for libpci you must install `libpci-dev` which depends on `libpci` and provides `/usr/include/pci/pci.h`. Same applies for the other dependencies.

**Comment by LinusDierheimer** [comment]
Can this be closed?

**Comment by whyadamsalt** [comment]
Yeah, there are some alternative "package managers" like pacstall which make it easier to install on Ubuntu.
